### ISSUE TITLE
Main to-do list

### ISSUE THREAD

**Issue by pajuaneza** [pajuaneza/hackit-mental-health#1]
- [x] Community support
  - [x] Find psychiatrists
  - [x] Group chats
  - [x] Friends
- [x] Personal progress
  - [x] Daily diary
  - [x] Mood tracker
  - [x] Monitoring statistics
- [x] Self-help
  - [x] Tips and advice
  - [x] Fun activities
  - [x] Videos and music
  - [x] Frequently asked questions
- [x] My account
  - [x] Account settings
  - [x] Points system
  - [ ] Achievements
